name: "Install"

on:
  schedule:
    - cron: '7 7 * * *'  # At 07:07 every day
  workflow_dispatch:

permissions:
  contents: read

jobs:
  scratch:
    name: "Install"
    runs-on: ubuntu-latest
    steps:

      - name: "PHP: setup 8.4"
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          coverage: none
          tools: composer

      - name: "Composer: require"
        run: composer require --dev smnandre/twigmetrics
        
      - name: "Composer: show"
        run: composer show -i "smnandre/twigmetrics"
        
      - name: "TwigMetrics: version"
        run: vendor/bin/twigmetrics --version
